name: Upload Transcript
on:
  repository_dispatch:
    types: [upload-transcript]

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite escrita no repositório
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save transcript
        run: |
          echo "${{ github.event.client_payload.file }}" | base64 -d > ${{ github.event.client_payload.filename }}

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ github.event.client_payload.filename }}
          git commit -m "Add transcript ${{ github.event.client_payload.filename }}"
          git fetch origin main
          git rebase origin/main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Continua mesmo se houver conflito

      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
